<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <title>teste</title>
</head>
<body>

        <h1>Cadastro de Artigos</h1>

        <a href="/">Home</a>
        <a href="/artigos/lista">Artigos</a>

        <hr>

        <form action="" method="post" enctype="multipart/form-data">

            <fieldset>
                <legend>Cadastrar Artigo</legend>

                <label for="titulo">Titulo: </label>
                <input type="text" name="titulo">

                <label for="titulo">Artigo: </label>
                <input type="text" name="artigo">


                <input type="submit" value="Cadastrar">


            </fieldset>

        </form>



        <hr>



</body>
</html>