<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>
    
<form method="post" action="admin">

   <fieldset>

        <legend>Login</legend>

        <label>Nome:</label>    
        <input type="text" name="nome" />

        <label>Senha:</label>    
        <input type="password" name="password" />

        <input type="submit" value="Login">

   </fieldset>

</form>

    <?php print_r($_SESSION); ?> <hr>

    


</body>
</html>